import { 
  Rocket, 
  Wrench, 
  GraduationCap,
  Layers,
  Waves,
  Calculator,
  Mountain,
  AlertTriangle,
  Milestone,
  Grid3X3
} from "lucide-react";
import { PathwayData } from "./PathwayCard";

export const learningPathways: PathwayData[] = [
  {
    id: "get-started",
    title: "Get Started",
    description: "Build your first river reach model from scratch. Learn the fundamentals of 1D hydraulic modeling step by step.",
    icon: <Rocket className="w-6 h-6" />,
    color: "primary",
    estimatedTime: "45 min",
    steps: [
      {
        id: "gs-1",
        title: "Explore the River Reach Diagram",
        description: "Understand the key components of a 1D river reach model by clicking through the interactive diagram.",
        duration: "5 min",
        sectionId: "diagram",
      },
      {
        id: "gs-2",
        title: "Learn Channel Geometry",
        description: "Use the Cross-Section view to understand trapezoidal channel geometry and key dimensions.",
        duration: "8 min",
        sectionId: "editor",
      },
      {
        id: "gs-3",
        title: "Understand Manning's Equation",
        description: "See how roughness, slope, and geometry combine to determine flow velocity and discharge.",
        duration: "10 min",
        sectionId: "editor",
      },
      {
        id: "gs-4",
        title: "Follow the Step-by-Step Guide",
        description: "Work through the complete modeling workflow: nodes, links, cross-sections, and boundary conditions.",
        duration: "15 min",
        sectionId: "steps",
      },
      {
        id: "gs-5",
        title: "Test Your Knowledge",
        description: "Take the quiz to reinforce key concepts you've learned.",
        duration: "7 min",
        sectionId: "quiz",
      },
    ],
  },
  {
    id: "solve-problem",
    title: "Solve a Problem",
    description: "Troubleshoot common modeling issues and learn diagnostic techniques to fix unstable or inaccurate simulations.",
    icon: <Wrench className="w-6 h-6" />,
    color: "terrain",
    estimatedTime: "30 min",
    steps: [
      {
        id: "sp-1",
        title: "Identify Numerical Oscillations",
        description: "Learn why oscillations occur and how Courant Number affects stability.",
        duration: "8 min",
        sectionId: "troubleshooting",
      },
      {
        id: "sp-2",
        title: "Fix Drying Channel Problems",
        description: "Understand minimum depth thresholds and how to handle intermittent flow.",
        duration: "6 min",
        sectionId: "troubleshooting",
      },
      {
        id: "sp-3",
        title: "Analyze Flow Regimes",
        description: "Use the Froude Number Calculator to identify subcritical, critical, and supercritical flow.",
        duration: "8 min",
        sectionId: "froude-calculator",
      },
      {
        id: "sp-4",
        title: "Understand Courant Number",
        description: "Learn the stability criterion and how timestep relates to wave speed.",
        duration: "8 min",
        sectionId: "advanced-concepts",
      },
    ],
  },
  {
    id: "master-culverts",
    title: "Master: Culvert Design",
    description: "Deep dive into culvert hydraulics including inlet/outlet control, HY-8 methodology, and ICM implementation.",
    icon: <Milestone className="w-6 h-6" />,
    color: "water",
    estimatedTime: "40 min",
    steps: [
      {
        id: "mc-1",
        title: "Culvert Flow Regimes",
        description: "Understand USBPR Types I, II, III and pressurized flow with the Bridge/Culvert visualizer.",
        duration: "10 min",
        sectionId: "editor",
      },
      {
        id: "mc-2",
        title: "Inlet vs Outlet Control",
        description: "Learn when each control type governs and how to calculate headwater.",
        duration: "8 min",
        sectionId: "culvert-calculator",
      },
      {
        id: "mc-3",
        title: "Size a Culvert with HY-8",
        description: "Use the Culvert Design Calculator to size pipe and box culverts for design flows.",
        duration: "12 min",
        sectionId: "culvert-calculator",
      },
      {
        id: "mc-4",
        title: "ICM Implementation Notes",
        description: "Learn how to set up culverts in InfoWorks ICM with correct parameters.",
        duration: "10 min",
        sectionId: "editor",
      },
    ],
  },
  {
    id: "master-gvf",
    title: "Master: Water Surface Profiles",
    description: "Understand gradually varied flow, profile classifications, and backwater calculations.",
    icon: <Waves className="w-6 h-6" />,
    color: "node",
    estimatedTime: "35 min",
    steps: [
      {
        id: "mg-1",
        title: "Normal & Critical Depth",
        description: "Calculate and interpret yn and yc for different channel slopes.",
        duration: "8 min",
        sectionId: "froude-calculator",
      },
      {
        id: "mg-2",
        title: "Profile Classifications",
        description: "Learn M1, M2, M3, S1, S2, S3 profiles and when each forms.",
        duration: "10 min",
        sectionId: "gvf-calculator",
      },
      {
        id: "mg-3",
        title: "Step-Backwater Method",
        description: "Use the GVF Profile Calculator to compute water surface profiles.",
        duration: "10 min",
        sectionId: "gvf-calculator",
      },
      {
        id: "mg-4",
        title: "Hydraulic Jumps",
        description: "Identify where jumps occur and calculate sequent depth.",
        duration: "7 min",
        sectionId: "froude-calculator",
      },
    ],
  },
  {
    id: "master-2d",
    title: "Master: 1D/2D Coupling",
    description: "Learn to set up coupled 1D/2D models for floodplain modeling with bank spills and 2D zones.",
    icon: <Grid3X3 className="w-6 h-6" />,
    color: "terrain",
    estimatedTime: "45 min",
    steps: [
      {
        id: "m2d-1",
        title: "Coupling Concepts",
        description: "Understand when and why to use 1D/2D coupled modeling.",
        duration: "8 min",
        sectionId: "editor",
      },
      {
        id: "m2d-2",
        title: "Bank Spill Setup",
        description: "Configure lateral spill connections between 1D channels and 2D zones.",
        duration: "12 min",
        sectionId: "2d-modeling",
      },
      {
        id: "m2d-3",
        title: "2D Mesh Design",
        description: "Learn mesh sizing, roughness zones, and computational considerations.",
        duration: "15 min",
        sectionId: "2d-modeling",
      },
      {
        id: "m2d-4",
        title: "Inline Banks & Breaches",
        description: "Model embankments and breach scenarios in the 2D domain.",
        duration: "10 min",
        sectionId: "2d-modeling",
      },
    ],
  },
];

// Section ID to scroll target mapping
export const sectionTargets: Record<string, string> = {
  "diagram": "diagram",
  "editor": "editor",
  "steps": "steps",
  "components": "components",
  "quiz": "quiz",
  "troubleshooting": "troubleshooting",
  "advanced-concepts": "advanced-concepts",
  "froude-calculator": "froude-calculator",
  "gvf-calculator": "gvf-calculator",
  "culvert-calculator": "culvert-calculator",
  "bridge-culvert": "bridge-culvert",
  "coupling-zones": "coupling-zones",
  "2d-modeling": "2d-modeling",
};
